// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: address_cache.sql

package cachedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const lookupAddressCacheByNormalized = `-- name: LookupAddressCacheByNormalized :one
SELECT
    raw_address,
    normalized_address,
    structured,
    source
FROM address_cache
WHERE normalized_address = $1
`

type LookupAddressCacheByNormalizedRow struct {
	RawAddress        string `json:"raw_address"`
	NormalizedAddress string `json:"normalized_address"`
	Structured        []byte `json:"structured"`
	Source            string `json:"source"`
}

func (q *Queries) LookupAddressCacheByNormalized(ctx context.Context, normalizedAddress string) (LookupAddressCacheByNormalizedRow, error) {
	row := q.db.QueryRow(ctx, lookupAddressCacheByNormalized, normalizedAddress)
	var i LookupAddressCacheByNormalizedRow
	err := row.Scan(
		&i.RawAddress,
		&i.NormalizedAddress,
		&i.Structured,
		&i.Source,
	)
	return i, err
}

const searchAddressCache = `-- name: SearchAddressCache :many
SELECT
    raw_address,
    normalized_address,
    structured,
    source,
    (1 - (embedding <=> $1::vector))::double precision AS semantic_score
FROM address_cache
ORDER BY embedding <=> $1::vector
LIMIT $2
`

type SearchAddressCacheParams struct {
	Embedding   string `json:"embedding"`
	ResultLimit int32  `json:"result_limit"`
}

type SearchAddressCacheRow struct {
	RawAddress        string  `json:"raw_address"`
	NormalizedAddress string  `json:"normalized_address"`
	Structured        []byte  `json:"structured"`
	Source            string  `json:"source"`
	SemanticScore     float64 `json:"semantic_score"`
}

func (q *Queries) SearchAddressCache(ctx context.Context, arg SearchAddressCacheParams) ([]SearchAddressCacheRow, error) {
	rows, err := q.db.Query(ctx, searchAddressCache, arg.Embedding, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchAddressCacheRow
	for rows.Next() {
		var i SearchAddressCacheRow
		if err := rows.Scan(
			&i.RawAddress,
			&i.NormalizedAddress,
			&i.Structured,
			&i.Source,
			&i.SemanticScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAddressCache = `-- name: UpsertAddressCache :exec
INSERT INTO address_cache (
    raw_address,
    normalized_address,
    embedding,
    source,
    structured,
    country_code,
    town,
    postal_code,
    street
) VALUES (
    $1,
    $2,
    $3::vector,
    $4,
    $5::jsonb,
    $6,
    $7,
    $8,
    $9
)
ON CONFLICT (normalized_address) DO UPDATE SET
    raw_address = EXCLUDED.raw_address,
    embedding = EXCLUDED.embedding,
    source = CASE
        WHEN address_cache.source = 'human_verified' AND EXCLUDED.source <> 'human_verified' THEN address_cache.source
        ELSE EXCLUDED.source
    END,
    structured = CASE
        WHEN address_cache.source = 'human_verified' AND EXCLUDED.source <> 'human_verified' THEN address_cache.structured
        ELSE EXCLUDED.structured
    END,
    country_code = CASE
        WHEN address_cache.source = 'human_verified' AND EXCLUDED.source <> 'human_verified' THEN address_cache.country_code
        ELSE EXCLUDED.country_code
    END,
    town = CASE
        WHEN address_cache.source = 'human_verified' AND EXCLUDED.source <> 'human_verified' THEN address_cache.town
        ELSE EXCLUDED.town
    END,
    postal_code = CASE
        WHEN address_cache.source = 'human_verified' AND EXCLUDED.source <> 'human_verified' THEN address_cache.postal_code
        ELSE EXCLUDED.postal_code
    END,
    street = CASE
        WHEN address_cache.source = 'human_verified' AND EXCLUDED.source <> 'human_verified' THEN address_cache.street
        ELSE EXCLUDED.street
    END,
    updated_at = now()
`

type UpsertAddressCacheParams struct {
	RawAddress        string      `json:"raw_address"`
	NormalizedAddress string      `json:"normalized_address"`
	Embedding         string      `json:"embedding"`
	Source            string      `json:"source"`
	Structured        []byte      `json:"structured"`
	CountryCode       pgtype.Text `json:"country_code"`
	Town              pgtype.Text `json:"town"`
	PostalCode        pgtype.Text `json:"postal_code"`
	Street            pgtype.Text `json:"street"`
}

func (q *Queries) UpsertAddressCache(ctx context.Context, arg UpsertAddressCacheParams) error {
	_, err := q.db.Exec(ctx, upsertAddressCache,
		arg.RawAddress,
		arg.NormalizedAddress,
		arg.Embedding,
		arg.Source,
		arg.Structured,
		arg.CountryCode,
		arg.Town,
		arg.PostalCode,
		arg.Street,
	)
	return err
}
