// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package cachedb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AddressCache struct {
	ID                int64              `json:"id"`
	RawAddress        string             `json:"raw_address"`
	NormalizedAddress string             `json:"normalized_address"`
	Embedding         string             `json:"embedding"`
	Source            string             `json:"source"`
	Structured        []byte             `json:"structured"`
	CountryCode       pgtype.Text        `json:"country_code"`
	Town              pgtype.Text        `json:"town"`
	PostalCode        pgtype.Text        `json:"postal_code"`
	Street            pgtype.Text        `json:"street"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}
