// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package cachedb

import (
	"context"
)

type Querier interface {
	LookupAddressCacheByNormalized(ctx context.Context, normalizedAddress string) (LookupAddressCacheByNormalizedRow, error)
	SearchAddressCache(ctx context.Context, arg SearchAddressCacheParams) ([]SearchAddressCacheRow, error)
	UpsertAddressCache(ctx context.Context, arg UpsertAddressCacheParams) error
}

var _ Querier = (*Queries)(nil)
